import type {
  ResolvedSpecSourceLevel,
  VerticalSolutionCode,
} from '@/lib/discovery/technical-spec-types';

export const RECIPE_CODE_CATALOG = [
  'RECIPE_ROOM_STD_COLIVING_BASIC_M2',
  'RECIPE_ROOM_STD_COLIVING_PLUS_M2',
  'RECIPE_BATH_STD_COMPACT_M2',
  'RECIPE_BATH_STD_MEDIUM_M2',
  'RECIPE_BATH_ADAPTED_M2',
  'RECIPE_KITCHENETTE_120_BASIC_ML',
  'RECIPE_KITCHENETTE_180_COMPLETE_ML',
  'RECIPE_LEVELING_LIGHT_M2',
  'RECIPE_LEVELING_MEDIUM_M2',
  'RECIPE_COMMON_AREA_BASIC_M2',
  'RECIPE_COMMON_AREA_INTENSIVE_M2',
  'RECIPE_PARTITION_PLADUR_STD_M2',
  'RECIPE_PARTITION_PLADUR_ACOUSTIC_M2',
  'RECIPE_PARTITION_BRICK_STD_M2',
  'RECIPE_PARTITION_BLOCK_STD_M2',
  'RECIPE_CEILING_CONTINUOUS_STD_M2',
  'RECIPE_CEILING_CONTINUOUS_INSULATED_M2',
  'RECIPE_CEILING_SUSPENDED_GRID_M2',
  'RECIPE_FLOOR_TILE_STD_M2',
  'RECIPE_FLOOR_LAMINATE_STD_M2',
  'RECIPE_FLOOR_VINYL_STD_M2',
  'RECIPE_SKIRTING_STD_ML',
  'RECIPE_DOOR_INTERIOR_STD_UD',
  'RECIPE_DOOR_INTERIOR_PLUS_UD',
  'RECIPE_WINDOW_STD_UD',
  'RECIPE_WINDOW_IMPROVED_UD',
  'RECIPE_SHUTTER_STD_UD',
  'RECIPE_ELECTRICAL_ROOM_STD_PT',
  'RECIPE_LIGHTING_BASIC_PT',
  'RECIPE_PLUMBING_POINT_STD_PT',
  'RECIPE_DRAINAGE_POINT_STD_PT',
  'RECIPE_WALL_TILE_BATH_STD_M2',
  'RECIPE_WALL_TILE_BATH_PLUS_M2',
  'RECIPE_WALL_TILE_KITCHEN_SPLASHBACK_M2',
  'RECIPE_PAINT_WALL_STD_M2',
  'RECIPE_PAINT_WALL_PLUS_M2',
  'RECIPE_PAINT_CEILING_STD_M2',
  'RECIPE_WET_AREA_WATERPROOFING_STD_M2',
  'RECIPE_PARTITION_LINING_STD_M2',
  'RECIPE_CEILING_CONTINUOUS_PLUS_M2',
  'RECIPE_DOOR_SLIDING_STD_UD',
  'RECIPE_DOOR_RF_BASIC_UD',
  'RECIPE_WINDOW_THERMAL_PLUS_UD',
  'RECIPE_ELECTRICAL_MECHANISMS_STD_PT',
  'RECIPE_ELECTRICAL_PANEL_BASIC_UD',
  'RECIPE_PLUMBING_WET_ROOM_STD_PT',
  'RECIPE_DRAINAGE_WET_ROOM_STD_PT',
] as const;

export type RecipeCode = (typeof RECIPE_CODE_CATALOG)[number];

export const MATERIAL_CODE_CATALOG = [
  'MAT_ROOM_FLOOR_BASIC',
  'MAT_ROOM_SKIRTING_BASIC',
  'MAT_ROOM_PAINT_BASIC',
  'MAT_ROOM_ELEC_PACK_BASIC',
  'MAT_ROOM_FLOOR_PLUS',
  'MAT_ROOM_SKIRTING_PLUS',
  'MAT_ROOM_PAINT_PLUS',
  'MAT_ROOM_ELEC_PACK_PLUS',
  'MAT_BATH_TILE_COMPACT',
  'MAT_BATH_FLOOR_COMPACT',
  'MAT_BATH_SANITARY_COMPACT',
  'MAT_BATH_PLUMBING_COMPACT',
  'MAT_BATH_DRAINAGE_COMPACT',
  'MAT_BATH_ELEC_COMPACT',
  'MAT_BATH_TILE_MEDIUM',
  'MAT_BATH_FLOOR_MEDIUM',
  'MAT_BATH_SANITARY_MEDIUM',
  'MAT_BATH_PLUMBING_MEDIUM',
  'MAT_BATH_DRAINAGE_MEDIUM',
  'MAT_BATH_ELEC_MEDIUM',
  'MAT_BATH_TILE_ADAPTED',
  'MAT_BATH_FLOOR_ADAPTED',
  'MAT_BATH_SANITARY_ADAPTED',
  'MAT_BATH_SUPPORTS_ADAPTED',
  'MAT_BATH_PLUMBING_ADAPTED',
  'MAT_BATH_DRAINAGE_ADAPTED',
  'MAT_BATH_ELEC_ADAPTED',
  'MAT_KITCH_BASE_CABINET',
  'MAT_KITCH_BASE_COUNTERTOP',
  'MAT_KITCH_BASE_SINK',
  'MAT_KITCH_BASE_CONNECTIONS',
  'MAT_KITCH_COMPLETE_CABINET',
  'MAT_KITCH_COMPLETE_COUNTERTOP',
  'MAT_KITCH_COMPLETE_SINK',
  'MAT_KITCH_COMPLETE_APPLIANCE_PACK',
  'MAT_KITCH_COMPLETE_CONNECTIONS',
  'MAT_LEVELING_LIGHT_MORTAR',
  'MAT_LEVELING_MEDIUM_MORTAR',
  'MAT_COMMON_FLOOR_BASIC',
  'MAT_COMMON_PAINT_BASIC',
  'MAT_COMMON_LIGHTING_BASIC',
  'MAT_COMMON_FLOOR_INTENSIVE',
  'MAT_COMMON_PAINT_INTENSIVE',
  'MAT_COMMON_LIGHTING_INTENSIVE',
  'MAT_COMMON_PROTECTION_INTENSIVE',
  'MAT_PARTITION_PLADUR_STD_FRAME',
  'MAT_PARTITION_PLADUR_STD_BOARD',
  'MAT_PARTITION_PLADUR_STD_FILL',
  'MAT_PARTITION_PLADUR_AC_FRAME',
  'MAT_PARTITION_PLADUR_AC_BOARD',
  'MAT_PARTITION_PLADUR_AC_FILL',
  'MAT_PARTITION_BRICK_STD_BLOCK',
  'MAT_PARTITION_BRICK_STD_MORTAR',
  'MAT_PARTITION_BLOCK_STD_BLOCK',
  'MAT_PARTITION_BLOCK_STD_MORTAR',
  'MAT_CEILING_CONT_STD_FRAME',
  'MAT_CEILING_CONT_STD_BOARD',
  'MAT_CEILING_CONT_INS_FRAME',
  'MAT_CEILING_CONT_INS_BOARD',
  'MAT_CEILING_CONT_INS_FILL',
  'MAT_CEILING_GRID_MAIN',
  'MAT_CEILING_GRID_TILE',
  'MAT_FLOOR_TILE_STD',
  'MAT_FLOOR_TILE_ADHESIVE',
  'MAT_FLOOR_LAMINATE_STD',
  'MAT_FLOOR_VINYL_STD',
  'MAT_SKIRTING_STD',
  'MAT_DOOR_INTERIOR_STD_SET',
  'MAT_DOOR_INTERIOR_PLUS_SET',
  'MAT_WINDOW_STD_SET',
  'MAT_WINDOW_IMPROVED_SET',
  'MAT_SHUTTER_STD_SET',
  'MAT_ELECTRICAL_POINT_STD',
  'MAT_LIGHTING_POINT_STD',
  'MAT_PLUMBING_POINT_STD',
  'MAT_DRAINAGE_POINT_STD',
  'MAT_WALL_TILE_BATH_STD',
  'MAT_WALL_TILE_BATH_PLUS',
  'MAT_WALL_TILE_KITCH_SPLASHBACK',
  'MAT_PAINT_WALL_STD',
  'MAT_PAINT_WALL_PLUS',
  'MAT_PAINT_CEILING_STD',
  'MAT_WATERPROOFING_STD',
  'MAT_PARTITION_LINING_FRAME',
  'MAT_PARTITION_LINING_BOARD',
  'MAT_PARTITION_LINING_FILL',
  'MAT_CEILING_CONT_PLUS_FRAME',
  'MAT_CEILING_CONT_PLUS_BOARD',
  'MAT_CEILING_CONT_PLUS_FILL',
  'MAT_DOOR_SLIDING_STD_SET',
  'MAT_DOOR_RF_BASIC_SET',
  'MAT_WINDOW_THERMAL_PLUS_SET',
  'MAT_ELECTRICAL_MECHANISMS_STD',
  'MAT_ELECTRICAL_PANEL_BASIC',
  'MAT_PLUMBING_WET_ROOM_STD',
  'MAT_DRAINAGE_WET_ROOM_STD',
] as const;

export type RecipeMaterialCode = (typeof MATERIAL_CODE_CATALOG)[number];

export const LABOR_CODE_CATALOG = [
  'LAB_ROOM_BASIC',
  'LAB_ROOM_PLUS',
  'LAB_BATH_COMPACT',
  'LAB_BATH_MEDIUM',
  'LAB_BATH_ADAPTED',
  'LAB_KITCH_BASIC',
  'LAB_KITCH_COMPLETE',
  'LAB_LEVELING_LIGHT',
  'LAB_LEVELING_MEDIUM',
  'LAB_COMMON_BASIC',
  'LAB_COMMON_INTENSIVE',
  'LAB_PARTITION_PLADUR_STD',
  'LAB_PARTITION_PLADUR_ACOUSTIC',
  'LAB_PARTITION_BRICK_STD',
  'LAB_PARTITION_BLOCK_STD',
  'LAB_CEILING_CONTINUOUS_STD',
  'LAB_CEILING_CONTINUOUS_INSULATED',
  'LAB_CEILING_SUSPENDED_GRID',
  'LAB_FLOOR_TILE_STD',
  'LAB_FLOOR_LAMINATE_STD',
  'LAB_FLOOR_VINYL_STD',
  'LAB_SKIRTING_STD',
  'LAB_DOOR_INTERIOR_STD',
  'LAB_DOOR_INTERIOR_PLUS',
  'LAB_WINDOW_STD',
  'LAB_WINDOW_IMPROVED',
  'LAB_SHUTTER_STD',
  'LAB_ELECTRICAL_POINT_STD',
  'LAB_LIGHTING_POINT_STD',
  'LAB_PLUMBING_POINT_STD',
  'LAB_DRAINAGE_POINT_STD',
  'LAB_WALL_TILE_BATH_STD',
  'LAB_WALL_TILE_BATH_PLUS',
  'LAB_WALL_TILE_KITCH_SPLASHBACK',
  'LAB_PAINT_WALL_STD',
  'LAB_PAINT_WALL_PLUS',
  'LAB_PAINT_CEILING_STD',
  'LAB_WATERPROOFING_STD',
  'LAB_PARTITION_LINING_STD',
  'LAB_CEILING_CONTINUOUS_PLUS',
  'LAB_DOOR_SLIDING_STD',
  'LAB_DOOR_RF_BASIC',
  'LAB_WINDOW_THERMAL_PLUS',
  'LAB_ELECTRICAL_MECHANISMS_STD',
  'LAB_ELECTRICAL_PANEL_BASIC',
  'LAB_PLUMBING_WET_ROOM_STD',
  'LAB_DRAINAGE_WET_ROOM_STD',
] as const;

export type RecipeLaborCode = (typeof LABOR_CODE_CATALOG)[number];

export type RecipeStatus =
  | 'RECIPE_RESOLVED'
  | 'RECIPE_PARTIAL'
  | 'RECIPE_MISSING';

export type RecipeMaterial = {
  materialCode: RecipeMaterialCode;
  description: string;
  quantity: number;
  unit: string;
  pricingStatus: 'PENDING';
};

export type RecipeLabor = {
  laborCode: RecipeLaborCode;
  description: string;
  quantity: number;
  unit: 'h' | 'jor';
};

export type RecipeLine = {
  id: string;
  spaceId: string;
  solutionCode: VerticalSolutionCode;
  measurementLineId: string;
  recipeCode: RecipeCode;
  description: string;
  status: RecipeStatus;
  materials: RecipeMaterial[];
  labor: RecipeLabor[];
  wasteFactor?: number | null;
  indirectFactor?: number | null;
  sourceLevel: ResolvedSpecSourceLevel;
  sourceRefId?: string;
  assumedFields: string[];
};

export type RecipeResult = {
  status: 'READY' | 'PARTIAL' | 'BLOCKED';
  lines: RecipeLine[];
  coverage: {
    resolvedRecipeLines: number;
    partialRecipeLines: number;
    missingRecipeLines: number;
    recipeCoveragePercent: number;
  };
  warnings: string[];
  assumptions: string[];
};
